hypadrie/events/urls.py
"""
Events app urls

"""
from django.conf.urls.defaults import *

urlpatterns = patterns('events.views',
                       (r'^$', 'public_list'),
                       (r'^(?P<event_id>\d+)$', 'public_events'),
                       (r'^(?P<event_id>\d+)/registered$', 'public_registered'),
                       (r'^(?P<event_id>\d+)/cancel/(?P<unid1>\w+)-(?P<unid2>\w+)-(?P<unid3>\w+)-(?P<unid4>\w+)-(?P<unid5>\w+)$', 'public_cancel'),
                       (r'^(?P<event_id>\d+)/confirm/(?P<unid1>\w+)-(?P<unid2>\w+)-(?P<unid3>\w+)-(?P<unid4>\w+)-(?P<unid5>\w+)$', 'public_confirm'),
                        (r'^search/$', 'search_events'),
)

hypadrie/urls.py
# -*- coding: utf-8 -*-
#
# Copyright (c) 2012 Rodolphe Quiedeville <rodolphe@quiedeville.org>
#
#     This program is free software: you can redistribute it and/or modify
#     it under the terms of the GNU General Public License as published by
#     the Free Software Foundation, either version 3 of the License, or
#     (at your option) any later version.
#
#     This program is distributed in the hope that it will be useful,
#     but WITHOUT ANY WARRANTY; without even the implied warranty of
#     MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#     GNU General Public License for more details.
#
#     You should have received a copy of the GNU General Public License
#     along with this program.  If not, see <http://www.gnu.org/licenses/>.
#
from django.conf.urls.defaults import *
from django.contrib.sitemaps import FlatPageSitemap, GenericSitemap
from django.views.generic.simple import redirect_to
from resa.models import Performance
from time import strftime, localtime
from tastypie.api import Api
from resa.api import ShowResource
from resa.api import EventResource
from resa.api import PerformanceResource
from resa.api import BookingResource
from resa.api_auth import ShowAuthResource
from resa.api_auth import EventAuthResource
from resa.api_auth import PerformanceAuthResource
from resa.api_auth import BookingAuthResource

# Implement API version 1
v1_api = Api(api_name='v1')
# Register Shows
v1_api.register(ShowResource())
v1_api.register(EventResource())
v1_api.register(PerformanceResource())
v1_api.register(BookingResource())
v1_api.register(ShowAuthResource())
v1_api.register(EventAuthResource())
v1_api.register(PerformanceAuthResource())
v1_api.register(BookingAuthResource())

# Uncomment the next two lines to enable the admin:
from django.contrib import admin
admin.autodiscover()

info_dict = {
    'queryset': Performance.objects.filter(published='True',date__gt=strftime("%Y-%m-%d %H:%M:%S", localtime())).order_by('date'),
    'date_field': 'date',
}

sitemaps = {
    'flatpages': FlatPageSitemap,
    'blog': GenericSitemap(info_dict, priority=0.5),
}

#
urlpatterns = patterns(
    '',
    (r'^api/', include(v1_api.urls)),
    (r'^$', 'resa.views.performances'),
    (r'^accounts/profile/', 'resa.views.profile'),
    (r'^accounts/', include('registration.urls')),
    (r'^events/', include('events.urls')),
    (r'^logout$', 'resa.views.logout_view'),
    (r'^carte$', 'resa.views.themap'),
    (r'^about/$', 'resa.views.about'),
    (r'^help/?$', 'resa.views.helpview'),
    (r'^contact/$', 'resa.views.contact'),
    (r'^spectacles/', 'resa.views.spectacles'),
    (r'^accounts/api/', 'resa.views.api'),
    (r'^accounts/spectacles/', 'resa.views.spectacle_list'),
    (r'^accounts/spectacle/nouveau/', 'resa.views.spectacle_new'),
    (r'^accounts/spectacle/(?P<show_id>\d+)$', 'resa.views.spectacle_file'),
    (r'^accounts/spectacle/(?P<show_id>\d+)/resa/$', 'resa.views.spectacle_resa'),
    (r'^spectacle/(?P<show_id>\d+)$', 'resa.views.spectacle'),
    (r'^place/(?P<place_id>\d+)/?$', 'resa.views.place'),
    (r'^resalist/(?P<performance_id>\d+)/delete/(?P<unid1>\w+)-(?P<unid2>\w+)-(?P<unid3>\w+)-(?P<unid4>\w+)-(?P<unid5>\w+)$', 'resa.views.booking_delete'),
    (r'^resalist/(?P<performance_id>\d+)/(?P<flag>\d?)', 'resa.views.booking_list'),
    (r'^resalist/email/(?P<email>.*)/', 'resa.views.booking_user_list'),
    (r'^resa/', 'resa.views.bookings'),
    (r'^representations/', 'resa.views.performances'),
    (r'^representation/(?P<performance_id>\d+)$', 'resa.views.performance'),
    (r'^representation/(?P<performance_id>\d+)/resa/$', 'resa.views.performance_resa'),
    (r'^representation/(?P<performance_id>\d+)/annulation/(?P<unid1>\w+)-(?P<unid2>\w+)-(?P<unid3>\w+)-(?P<unid4>\w+)-(?P<unid5>\w+)$', 'resa.views.performance_resa_cancel'),
    (r'^representation/(?P<performance_id>\d+)/pdf/$', 'resa.views.list_resa_pdf'),
    (r'^representation/(?P<performance_id>\d+)/csv/$', 'resa.views.list_resa_csv'),
    (r'^p/(?P<performance_id>\d+)/c/(?P<unid1>\w+)-(?P<unid2>\w+)-(?P<unid3>\w+)-(?P<unid4>\w+)-(?P<unid5>\w+)$', 'resa.views.performance_resa_cancel'),
    # Uncomment the admin/doc line below to enable admin documentation:
    (r'^admin/doc/', include('django.contrib.admindocs.urls')),   
    # Uncomment the next line to enable the admin:
    (r'^admin/', include(admin.site.urls)),
    (r'^search/', include('haystack.urls')),
    # Festivals
    (r'^(?P<festival_slug>\w+)/$', 'resa.views.festival'),
    (r'^(?P<festival_slug>\w+)/representations/$', 'resa.views.festival_performances'),
    (r'^(?P<festival_slug>\w+)/representation/(?P<performance_id>\d+)$', 'resa.views.performance'),
    (r'^(?P<festival_slug>\w+)/representation/(?P<performance_id>\d+)/resa/$', 'resa.views.performance_resa'),
    (r'^(?P<festival_slug>\w+)/representation/(?P<performance_id>\d+)/annulation/(?P<unid1>\w+)-(?P<unid2>\w+)-(?P<unid3>\w+)-(?P<unid4>\w+)-(?P<unid5>\w+)$', 'resa.views.performance_resa_cancel'),
    (r'^(?P<festival_slug>\w+)/representation/(?P<performance_id>\d+)/pdf/$', 'resa.views.list_resa_pdf'),
    (r'^(?P<festival_slug>\w+)/representation/(?P<performance_id>\d+)/csv/$', 'resa.views.list_resa_csv'),
    (r'^(?P<festival_slug>\w+)/representation/(?P<festival_id>\d+)/festival/csv/$', 'resa.views.list_resa_festival_csv'),
    (r'^(?P<festival_slug>\w+)/logout$', 'resa.views.logout_view'),
    (r'^(?P<festival_slug>\w+)/carte$', 'resa.views.themap'),
    (r'^(?P<festival_slug>\w+)/about/$', 'resa.views.about'),
    (r'^(?P<festival_slug>\w+)/help/?$', 'resa.views.helpview'),
    (r'^(?P<festival_slug>\w+)/contact/$', 'resa.views.contact'),
    (r'^(?P<festival_slug>\w+)/spectacles/', 'resa.views.spectacles'),
    (r'^(?P<festival_slug>\w+)/spectacle/(?P<show_id>\d+)$', 'resa.views.spectacle'),
    (r'^(?P<festival_slug>\w+)/resalist/(?P<performance_id>\d+)/delete/(?P<unid1>\w+)-(?P<unid2>\w+)-(?P<unid3>\w+)-(?P<unid4>\w+)-(?P<unid5>\w+)$', 'resa.views.booking_delete'),
    (r'^(?P<festival_slug>\w+)/resalist/(?P<performance_id>\d+)/(?P<flag>\d?)', 'resa.views.booking_list'),
    (r'^(?P<festival_slug>\w+)/resa/', 'resa.views.bookings'),
    (r'^(?P<festival_slug>\w+)/p/(?P<performance_id>\d+)/c/(?P<unid1>\w+)-(?P<unid2>\w+)-(?P<unid3>\w+)-(?P<unid4>\w+)-(?P<unid5>\w+)$', 'resa.views.performance_resa_cancel'),
    #
    #
    (r'^sitemap\.xml$', 'django.contrib.sitemaps.views.sitemap', {'sitemaps': sitemaps})
    #(r'^sitemap\.xml$', 'django.contrib.sitemaps.views.sitemap', HypadrieSitemap())
)

hypadrie/events/models.py
# -*- coding: utf-8 -*-  pylint: disable-msg=R0801
#
# Copyright (c) 2012 Rodolphe Quiédeville <rodolphe@quiedeville.org>
#
#     This program is free software: you can redistribute it and/or modify
#     it under the terms of the GNU General Public License as published by
#     the Free Software Foundation, either version 3 of the License, or
#     (at your option) any later version.
#
#     This program is distributed in the hope that it will be useful,
#     but WITHOUT ANY WARRANTY; without even the implied warranty of
#     MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#     GNU General Public License for more details.
#
#     You should have received a copy of the GNU General Public License
#     along with this program.  If not, see <http://www.gnu.org/licenses/>.
#
"""
This file is only for testing purpose
"""

hypadrie/events/forms.py
# -*- coding: utf-8 -*-
#
# Copyright (c) 2012 Rodolphe Quiédeville <rodolphe@quiedeville.org>
#
#     This program is free software: you can redistribute it and/or modify
#     it under the terms of the GNU General Public License as published by
#     the Free Software Foundation, either version 3 of the License, or
#     (at your option) any later version.
#
#     This program is distributed in the hope that it will be useful,
#     but WITHOUT ANY WARRANTY; without even the implied warranty of
#     MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#     GNU General Public License for more details.
#
#     You should have received a copy of the GNU General Public License
#     along with this program.  If not, see <http://www.gnu.org/licenses/>.
#
from django import forms
from django.forms.widgets import Select, TextInput, Textarea
from django.forms.widgets import CheckboxInput


class EventForm(forms.Form):

    firstname = forms.CharField(
        required=True,
        max_length=25,
        widget=TextInput(attrs={'class': 'input-large focused'}))

    name = forms.CharField(
        required=False,
        max_length=40,
        widget=TextInput(attrs={'class': 'input-large'}))

    nb_place_a = forms.ChoiceField(
        required=False,
        widget=Select(attrs={'class': 'span1'}))

    email = forms.EmailField(
        required=False,
        max_length=150,
        widget=TextInput(attrs={'class': 'input-xlarge'}))

    handicap = forms.BooleanField(
        required=False,
        widget=CheckboxInput())

    handicap_type = forms.BooleanField(
        required=False,
        widget=CheckboxInput())

    handicap_comment = forms.CharField(
        required=False,
        max_length=40,
        widget=TextInput(attrs={'class': 'input-large'}))

    handicap_contact = forms.BooleanField(
        required=False,
        widget=CheckboxInput())

    def __init__(self, *args, **kwargs):
        self.maxplaces = kwargs.pop('maxplaces', None)
        email_requ = kwargs.pop('email_required', None)
        super(EventForm, self).__init__(*args, **kwargs)
        if email_requ:
            self.fields['email'].required = email_requ

    def clean(self):
        cleaned_data = self.cleaned_data

        total = 1

        text = """
Pas assez de place disponible, il ne reste que %s places,
vous en avez demandé %s.
"""

        if self.maxplaces is None:
            msg = "Impossible d'enregistrer votre réservation"
            raise forms.ValidationError(msg)
        else:
            if (total > int(self.maxplaces)):
                msg = text % (self.maxplaces, total)
                raise forms.ValidationError(msg)
            if (total == 0):
                raise forms.ValidationError(msg_tot0)

        return cleaned_data

hypadrie/haystack/forms.py
from django import forms
from django.db import models
from django.utils.text import capfirst
from django.utils.translation import ugettext_lazy as _
from django.utils.encoding import smart_unicode
from haystack import connections
from haystack.constants import DEFAULT_ALIAS
from haystack.query import SearchQuerySet, EmptySearchQuerySet


def model_choices(using=DEFAULT_ALIAS):
    choices = [("%s.%s" % (m._meta.app_label, m._meta.module_name), capfirst(smart_unicode(m._meta.verbose_name_plural))) for m in connections[using].get_unified_index().get_indexed_models()]
    return sorted(choices, key=lambda x: x[1])


class SearchForm(forms.Form):
    q = forms.CharField(required=False, label=_('Search'))

    def __init__(self, *args, **kwargs):
        self.searchqueryset = kwargs.pop('searchqueryset', None)
        self.load_all = kwargs.pop('load_all', False)

        if self.searchqueryset is None:
            self.searchqueryset = SearchQuerySet()

        super(SearchForm, self).__init__(*args, **kwargs)

    def no_query_found(self):
        """
        Determines the behavior when no query was found.

        By default, no results are returned (``EmptySearchQuerySet``).

        Should you want to show all results, override this method in your
        own ``SearchForm`` subclass and do ``return self.searchqueryset.all()``.
        """
        return EmptySearchQuerySet()

    def search(self):
        if not self.is_valid():
            return self.no_query_found()

        if not self.cleaned_data.get('q'):
            return self.no_query_found()

        sqs = self.searchqueryset.auto_query(self.cleaned_data['q'])

        if self.load_all:
            sqs = sqs.load_all()

        return sqs

    def get_suggestion(self):
        if not self.is_valid():
            return None

        return self.searchqueryset.spelling_suggestion(self.cleaned_data['q'])


class HighlightedSearchForm(SearchForm):
    def search(self):
        return super(HighlightedSearchForm, self).search().highlight()


class FacetedSearchForm(SearchForm):
    def __init__(self, *args, **kwargs):
        self.selected_facets = kwargs.pop("selected_facets", [])
        super(FacetedSearchForm, self).__init__(*args, **kwargs)

    def search(self):
        sqs = super(FacetedSearchForm, self).search()

        # We need to process each facet to ensure that the field name and the
        # value are quoted correctly and separately:
        for facet in self.selected_facets:
            if ":" not in facet:
                continue

            field, value = facet.split(":", 1)

            if value:
                sqs = sqs.narrow(u'%s:"%s"' % (field, sqs.query.clean(value)))

        return sqs


class ModelSearchForm(SearchForm):
    def __init__(self, *args, **kwargs):
        super(ModelSearchForm, self).__init__(*args, **kwargs)
        self.fields['models'] = forms.MultipleChoiceField(choices=model_choices(), required=False, label=_('Search In'), widget=forms.CheckboxSelectMultiple)

    def get_models(self):
        """Return an alphabetical list of model classes in the index."""
        search_models = []

        if self.is_valid():
            for model in self.cleaned_data['models']:
                search_models.append(models.get_model(*model.split('.')))

        return search_models

    def search(self):
        sqs = super(ModelSearchForm, self).search()
        return sqs.models(*self.get_models())


class HighlightedModelSearchForm(ModelSearchForm):
    def search(self):
        return super(HighlightedModelSearchForm, self).search().highlight()


class FacetedModelSearchForm(ModelSearchForm):
    selected_facets = forms.CharField(required=False, widget=forms.HiddenInput)

    def search(self):
        sqs = super(FacetedModelSearchForm, self).search()

        if hasattr(self, 'cleaned_data') and self.cleaned_data['selected_facets']:
            sqs = sqs.narrow(self.cleaned_data['selected_facets'])

        return sqs.models(*self.get_models())

hypadrie/events/templates/events/cancel.html
{% load i18n %}
{% include "events/header.html" %}
{% include "events/navbar.html" %}

<div class="container">
  <div class="row">

    <div class="span9">
      <div>
	<table class="table table-bordered">
	  <tr>
	    <td>{% trans "Event" %}</td>
	    <td colspan="4"><strong>{{ event.show }}</strong></td>
	  </tr>
	  <tr>
	    <td>{% trans "Date" %}</td>
	    <td colspan="4">
	      {{event.date|date:"l j F Y H:i" }}
	    </td>
	  </tr>	  
	  <tr>
	    <td>{% trans "RoomPlace" %}</td>
	    <td colspan="4">{{ event.place }}, {{ event.place.town }}</td>
	  </tr>
	</table>      
      </div>
      
      {% if result == 'success' %}
      <div class="alert alert-success">
	<p>Votre réservation {{uuid}} a été annulée</p>
      </div>
      {% endif %}
      {% if result == 'notexist' %}
      <div class="alert alert-danger">
	<p>Ce numéro de billet n'existe pas : {{uuid}}</p>
      </div>
      {% endif %}
    </div><!--/span-->

    <!-- Rigth panel -->
    <div class="span3">
      {% include "events/last_events.html" %}
      {% if event.booking_is_open and not event.is_complete %}
      {% include "events/free_places.html" %}
      {% endif %}
      <div class="well sidebar-nav">
	<ul class="nav nav-list">
	  <li><a href="/events/{{ event.id }}/registered">{% trans "Registered" %}</a></li>
	</ul>	  
      </div><!--/.well -->

      {% include "events/right.html" %}
    </div>
    <!-- /Rigtht panel -->


  </div><!--/row-->
  
</div><!--/.container-->

{% include "events/footer.html" %}

hypadrie/events/templates/events/confirm.html
{% load i18n %}
{% include "events/header.html" %}
{% include "events/navbar.html" %}

<div class="container">
  <div class="row">

    <div class="span9">
      <div>
	<table class="table table-bordered">
	  <tr>
	    <td>{% trans "Event" %}</td>
	    <td colspan="4"><strong>{{ event.show }}</strong></td>
	  </tr>
	  <tr>
	    <td>{% trans "Date" %}</td>
	    <td colspan="4">
	      {{event.date|date:"l j F Y H:i" }}
	    </td>
	  </tr>	  
	  <tr>
	    <td>{% trans "RoomPlace" %}</td>
	    <td colspan="4">{{ event.place }}, {{ event.place.town }}</td>
	  </tr>
	</table>      
      </div>
      
      {% if result == 'success' %}
      <div class="alert alert-success">
	<p>
	  {% trans "Number :" %} {{uuid}}
	</p>
	<p>
	  {% trans "Your booking is now confirmed, thank you" %}
	</p>
      </div>
      {% endif %}
      {% if result == 'notexist' %}
      <div class="alert alert-danger">
	<p>
	  {% trans "Number :" %} {{uuid}}
	  </p><p>
	  {% trans "Sorry but we can't find any booking with this number, maybe it does not exists " %}
	  </p>
      </div>
      {% endif %}
    </div><!--/span-->

    <!-- Rigth panel -->
    <div class="span3">
      {% include "events/last_events.html" %}
      {% if event.booking_is_open and not event.is_complete %}
      {% include "events/free_places.html" %}
      {% endif %}
      <div class="well sidebar-nav">
	<ul class="nav nav-list">
	  <li><a href="/events/{{ event.id }}/registered">{% trans "Registered" %}</a></li>
	</ul>	  
      </div><!--/.well -->

      {% include "events/right.html" %}
    </div>
    <!-- /Rigtht panel -->


  </div><!--/row-->
  
</div><!--/.container-->

{% include "events/footer.html" %}

hypadrie/events/templates/events/event.html
{% load i18n %}
{% include "events/header.html" %}
{% include "events/navbar.html" %}

<div class="container">
  <div class="row">

    <div class="span9">
      
      <div>
	<table class="table table-bordered">
	  <tr>
	    <td>{% trans "Event" %}</td>
	    <td colspan="4"><strong>{{ event.show }}</strong></td>
	  </tr>
	  <tr>
	    <td>{% trans "Date" %}</td>
	    <td colspan="4">
	      {{event.date|date:"l j F Y H:i" }}
	    </td>
	  </tr>	  
	  <tr>
	    <td>{% trans "RoomPlace" %}</td>
	    <td colspan="4">{{ event.place }}, {{ event.place.town }}</td>
	  </tr>
	</table>      
      </div>
            
      {% if event.booking_is_open and not event.is_complete %}

      {% if form.non_field_errors %}
      <div class="alert alert-error">
	{{ form.non_field_errors }}
      </div>
      {% endif %}
      
      <form class="well form-horizontal" action="/events/{{event.id}}" method="post">
	{% csrf_token %}
	<fieldset>
	  
	  <div class="control-group">
	    <label class="control-label" for="firstname">{% trans "Firstname" %}</label>
	    <div class="controls">
	      {{form.firstname}}
	      {{form.firstname.errors}}
	    </div>
	  </div>
	  
	  <div class="control-group">
	    <label class="control-label" for="name">{% trans "Name" %}</label>
	    <div class="controls">
	      {{form.name}}
	      {{form.name.errors}}
	    </div>
	  </div>
	  
	  <div class="control-group">
	    <label class="control-label" for="email">{% trans "email" %}</label>
	    <div class="controls">
	      {{form.email}}
	      {{form.email.errors}}
	    </div>
	  </div>
	  
	  <div class="control-group">
	    <label class="control-label" for="firstname">{% trans "Handicap" %}</label>
	    <div class="controls">
	      {{form.handicap}}
	    </div>
	  </div>
	  
	  <div class="control-group">
	    <div class="controls">
	      <input id="book_btn" type="submit" class="btn btn-primary" value="{% trans "ToBook" %}" />
	    </div>
	  </div>	    
	</fieldset>
	
	<div >
	  <div class="control-group">
	    <label class="control-label" for="firstname">{% trans "Firstname" %}</label>
	    <div class="controls">
	      {{form.handicap_comment}}
	    </div>
	  </div>
	</div>

      </form>
      {% else %}
      <div>
	{% if event.is_complete %}
	<div class="alert alert-error">Complet, il n'y a plus de places disponibles.</div>
	{% else %}
	<div class="alert alert-info">La réservation pour ce spectacle est fermée.</div>
	{% endif %}
      </div>
      {% endif %}
            
      {% if bookings %}
      {% include "events/sub_registered.html" %}
      {% endif %}	
    </div><!--/span-->
    <!-- Rigth panel -->
    <div class="span3">
      {% include "events/last_events.html" %}
      {% if event.booking_is_open and not event.is_complete %}
      {% include "events/free_places.html" %}
      {% endif %}
      
      {% if event.public_booking %}
      <div class="well sidebar-nav">
	<ul class="nav nav-list">
	  <li><a href="/events/{{ event.id }}/registered">{% trans "Registered" %}</a></li>
	</ul>	  
      </div><!--/.well -->
      {% endif %}

      {% include "events/right.html" %}
    </div>
    <!-- /Rigtht panel -->
  </div><!--/row-->
  
</div><!--/.container-->
  
{% include "events/footer.html" %}

hypadrie/events/templates/events/event_success.html
{% load i18n %}
{% include "events/header.html" %}
{% include "events/navbar.html" %}

<div class="container">
  <div class="row">

    <div class="span9">
      
      <div>
	<table class="table table-bordered">
	  <tr>
	    <td>{% trans "Event" %}</td>
	    <td colspan="4"><strong>{{ event.show }}</strong></td>
	  </tr>
	  <tr>
	    <td>{% trans "Date" %}</td>
	    <td colspan="4">
	      {{event.date|date:"l j F Y H:i" }}
	    </td>
	  </tr>	  
	  <tr>
	    <td>{% trans "RoomPlace" %}</td>
	    <td colspan="4">{{ event.place }}, {{ event.place.town }}</td>
	  </tr>
	</table>      
      </div>
                      
      <div class="alert alert-success">

	<p>{% trans "Thanks for your booking, please find here your book number :" %} {{event.uuid}}</p>
	<p>{% trans "You'll receive an email with your booking number, remind to check your spam folder if you don't see the email in you inbox." %}
	  {% trans "The email sender is :" %} {{email_from}}
	  </p>
	<p>
	  {% trans "Your informations :" %}
	  <ul>
	    <li>{{bkn.firstname}} {{bkn.name}}</li>
	    <li>{{bkn.email}}</li>
	  </ul>
      </div>

      {% if event.require_confirmation %}
      <div class="alert alert-info">
	Vous allez reçevoir un email qui contient une url vous
	permettant de confirmer votre inscription. Votre inscription
	de deviendra définitive qu'après avoir cliqué sur le lien.
      </div>
      {% endif %}
      
      <div class="alert alert-info">
	{% trans "You can cancel your registration by clicking " %}
	<span class="btn btn-cancel">
	  <a href="/events/{{event.id}}/cancel/{{bkn.uuid}}">Cancel</a>
	</span>
      </div>

            
      {% if bookings %}
      {% include "events/sub_registered.html" %}
      {% endif %}	
    </div><!--/span-->
    <!-- Rigth panel -->
    <div class="span3">
      {% include "events/last_events.html" %}
      {% if event.booking_is_open and not event.is_complete %}
      {% include "events/free_places.html" %}
      {% endif %}
      <div class="well sidebar-nav">
	<ul class="nav nav-list">
	  <li><a href="/events/{{ event.id }}/registered">{% trans "Registered" %}</a></li>
	</ul>	  
      </div><!--/.well -->

      {% include "events/right.html" %}
    </div>
    <!-- /Rigtht panel -->
  </div><!--/row-->
  
</div><!--/.container-->
  
{% include "events/footer.html" %}

hypadrie/events/templates/events/last_events.html
{% load i18n %}
<!-- infobox in left.html -->
<div class="well sidebar-nav">
  <ul class="nav nav-list">
    {% for event in last_events %}
    <li><a href="/events/{{ event.id }}">{{ event.show.title }}</a></li>
    {% endfor %}
  </ul>	  
</div><!--/.well -->

hypadrie/events/templates/events/search.html
{% load i18n %}
{% include "events/header.html" %}
{% include "events/navbar.html" %}
<div class="container">
  <div class="row">    
    <div class="span9">      

<h2>{% trans "Search" %}</h2>

<form method="get" action=".">
  <fieldset>

    <input type="text" name="q" value="{{query}}" id="id_q" />
    
    <input class="btn-success" type="submit" value="{% trans 'Search' %}">
      
  </fieldset>
      
  {% if query %}
  <h3>{% trans "Results" %}</h3>
  <ul>
    {% for entry in results %}
    <li>
      <a href="/events/{{entry.id}}">{{ entry.show.title}}</a>
    </li>
    {% empty %}
    <li>{% trans "No results found." %}</li>
    {% endfor %}
  </ul>
  
  {% if page.has_previous or page.has_next %}
  <div>
    {% if page.has_previous %}<a href="?q={{ query }}&amp;page={{ page.previous_page_number }}">{% endif %}&laquo; Previous{% if page.has_previous %}</a>{% endif %}
    |
    {% if page.has_next %}<a href="?q={{ query }}&amp;page={{ page.next_page_number }}">{% endif %}Next &raquo;{% if page.has_next %}</a>{% endif %}
  </div>
  {% endif %}
  {% else %}
  {# Show some example queries to run, maybe query syntax, something else? #}
  {% endif %}
</form>

    </div><!--/span-->

    <!-- Rigth panel -->
    <div class="span3">
      {% include "events/last_events.html" %}
      {% include "events/right.html" %}
    </div>
    <!-- /Rigtht panel -->

  </div><!--/row-->  
</div><!--/.container-->
{% include "events/footer.html" %}